import PDFDocument from "pdfkit";

export const generateReportCardPdf = ({ student, marks, attendance }) =>
  new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 40 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    doc.fontSize(22).text("Student Report Card", { align: "center" });
    doc.moveDown();
    doc.fontSize(12).text(`Name: ${student.name}`);
    doc.text(`Admission No: ${student.studentProfile?.admissionNumber || "N/A"}`);
    doc.text(`Class: ${student.studentProfile?.className || "N/A"}`);
    doc.text(`Email: ${student.email}`);
    doc.moveDown();

    doc.fontSize(16).text("Attendance Summary");
    doc.fontSize(12).text(
      `Present: ${attendance.present} | Absent: ${attendance.absent} | Late: ${attendance.late}`
    );
    doc.moveDown();

    doc.fontSize(16).text("Marks");
    marks.forEach((mark) => {
      doc
        .fontSize(12)
        .text(
          `${mark.subject}: ${mark.score}/${mark.maximumScore} (${mark.grade})`
        );
    });

    doc.moveDown();
    doc.fontSize(10).text("Generated by Student Management System.");
    doc.end();
  });
